export const UPDATE_DETAILDATA = 'UPDATE_DETAILDATA';

export const UPDATE_SENSESDATA = 'UPDATE_SENSESDATA'

export const UPDATE_SEARCHRS = 'UPDATE_SEARCHRS';

export const INIT_DETAILDATA = 'INIT_DETAILDATA';

export const INIT_SENSESDATA ='INIT_SENSESDATA';

export const UPDATE_USERINFO = 'UPDATE_USERINFO'

export const UPDATE_USERSENSES = 'UPDATE_USERSENSES'

export const INIT_USERID = 'INIT_USERID'

export const INIT_USERSENSES = 'INIT_USERSENSES'

export const UPDATE_USEROWNCHANNEL = 'UPDATE_USEROWNCHANNEL';

export const UPDATE_OWNINFO = 'UPDATE_OWNINFO';

export const INIT_USERCHENNEL = 'INIT_USERCHENNEL';
